version: 0.2
phases:
  pre_build:
    commands:
    - echo PRE BUILD PHASE
    - echo $dockerpass | docker login --username $dockeruser --password-stdin 
  build:
    commands:
    - echo Build started on `date`
    - cd mysqlcon
    - docker build -t mysqldockimage:sql .
    - cd ..
    - cd phpapp 
    - docker build -t phpimage:php --no-cache .
    - cd ..
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s5o7d0z2
    - docker tag mysqldockimage:sql public.ecr.aws/s5o7d0z2/ak-phpmysql:mysql
    - docker tag phpimage:php public.ecr.aws/s5o7d0z2/ak-phpmysql:phpimage
    - docker push public.ecr.aws/s5o7d0z2/ak-phpmysql:phpimage
    - docker push public.ecr.aws/s5o7d0z2/ak-phpmysql:mysql
  post_build:
    commands:
    - echo Build completed on `date`
    - printf '[{"name":"phpcontainer","imageUri":"public.ecr.aws/s5o7d0z2/ak-phpmysql:phpimage"},\n{"name":"mysqlcontainer","imageUri":"public.ecr.aws/s5o7d0z2/ak-phpmysql:mysql"}]' > imagedefinitions.json
  artifacts:
    files:
    - 'imagedefinitions.json'
   
